
exp_name: 'inv_dd_rev_noInvH'
output_dir: './output/'

# dataset config
dataset:
  fn: './datasets/mnist.py'
  name: 'MNIST'
  mean: [0.1307]
  std: [0.3081]
  num_classes: 10
  num_channel: 1
  
train:
  adjust_iter_num: [40000]